correo/base/urls.py
from django.conf.urls import patterns, url
from base import views

urlpatterns= patterns('',
        url(r'^$', views.index, name='index'),
        url(r'^home/$', views.home, name='home'),
	url(r'^login/$', views.user_login, name='login'),
        url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^mailbox/$', views.mailbox, name='mailbox'),
	url(r'^domain/$', views.domain, name='domain'),


	#url(r'^activar/new/$', views.activar_doble_factor, name='activar'),
	#url(r'^activar/persist/$', views.activar_doble_factor, name='activar'),
	)

correo/correo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'correo.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('base.urls')),
)

correo/base/models.py
from django.db import models

class Aliases(models.Model):
    pkid = models.AutoField(primary_key=True)
    mail = models.CharField(unique=True, max_length=120)
    destination = models.CharField(max_length=120)
    enabled = models.IntegerField(default=1)
    class Meta:
        db_table = 'aliases'

class Domains(models.Model):
    pkid = models.AutoField(primary_key=True)
    domain = models.CharField(max_length=120)
    transport = models.CharField(max_length=120, default='virtual:')
    enabled = models.IntegerField(default=1)
    class Meta:
        db_table = 'domains'

class Users(models.Model):
    id = models.CharField(primary_key= True, unique=True, max_length=128)
    name = models.CharField(max_length=128)
    uid = models.IntegerField(default=5000)
    gid = models.IntegerField(default=5000)
    home = models.CharField(max_length=255, default='/var/spool/mail/virtual')
    maildir = models.CharField(max_length=255, default='blah/')
    enabled = models.IntegerField(default=1)
    change_password = models.IntegerField(default=1)
    crypt = models.CharField(max_length=128, default='sdtrusfX0Jj66')
    clear = models.CharField(max_length=128, default='ChangeMe')
    quota = models.CharField(max_length=255, default='')
    
    class Meta:
	db_table = 'users'

correo/base/forms.py
from django import forms
from django.contrib.auth.models import User
from base.models import Users

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'email', 'password')


class MailForm(forms.ModelForm):
        crypt = forms.CharField(widget=forms.PasswordInput())

        class Meta:
                model = Users
                fields = ('name', 'crypt')

correo/base/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from base.forms import UserForm, MailForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from base.models import Users, Domains, Aliases
from django.core.mail import send_mail
import random, crypt


def index(request):   
    #creamos un diccionario para pasar al template
    context_dict = {'variable': "Vengo de la vista y soy una variable"}
    if request.user.is_authenticated():
	#return render(request, 'base/home.html')
	return HttpResponseRedirect('/home/')    

    return render(request, 'base/index.html', context_dict)

@login_required(login_url='/')
def home(request):   
	return render(request, 'base/home.html', {'security': 'actived'})

def user_login(request):
	if request.user.is_authenticated():
		return HttpResponseRedirect('/home/')
	if request.method == 'POST':
        	#capturamos los datos del formulario de inicio de sesion
        	username = request.POST['username']
        	password = request.POST['password']
	
		user = authenticate(username=username, password=password)

		if user:
    			if user.is_active:
                		login(request, user)
                		return HttpResponseRedirect('/home/')
           	 	else:
                		return HttpResponse("Tu usuario esta desactivado")
        	else:
            		return render(request, 'base/index.html', {'error_login': 'Hubo un error en el login'})
	else:
        	if not request.user.is_authenticated():
           		return render(request, 'base/index.html', {})
        	else:
            		return HttpResponseRedirect('/home/') 

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')

@login_required
def mailbox(request):

	domain_list= Domains.objects.all()
	registered= False
	if request.method == 'POST':
		req_dict= request.POST.dict()
		if req_dict['list'] == None:
			return render(request, 'base/mailbox.html', {'error_msg': 'Debe seleccionar un dominio', 'domain_list':domain_list})
		mail_form = MailForm(data=request.POST)
		mail= mail_form.save(commit=False)
		if mail_form.is_valid():
			try:
				name_valid= Users.objects.get(name=mail.name)
				return render(request, 'base/mailbox.html', {'error_msg': mail.name, 'domain_list': domain_list})
			except:
				pass
			salt= "$5$"+str(random.random())
			crypt_form= crypt.crypt(mail.crypt, salt)
			maildir_form= str(mail.name)+str("/")
			id_form= str(mail.name)+str('@')+str(req_dict['list'])
			name_form= str(mail.name)

			u= Users(id= id_form, name=name_form, maildir=maildir_form, crypt=crypt_form)
			a= Aliases(mail= id_form, destination= id_form)
			a.save()
			u.save()
			send_mail('Bienvenido al correo Ardilla', 'No responda este correo', 'no-reply@ardilla.com.ar', [id_form], fail_silently=False)

			registered = True
			return render(request, 'base/home.html', {'register_msg': 'Registro satisfactorio, ya puede usar su usuario en http://ardilla.com.ar/webmail/'} )
		else:
			return render(request, 'base/mailbox.html', {'error_msg': 'Error en campos ', 'domain_list': domain_list})
	else:
		#devolvemos un formulario al template
		mail_form = MailForm()
		return render(request, 'base/mailbox.html', {'user_form': mail_form, 'domain_list': domain_list})

@login_required
def domain(request):

	domain_list= Domains.objects.all()
	if request.method == 'POST':
		req_dict= request.POST.dict()
		if req_dict['domain'] == None:
			return render(request, 'base/domain.html', {'error_msg': 'Debe ingresar un dominio', 'domain_list':domain_list})
		try:
			domain_valid= Domains.objects.get(domain=req_dict['domain'])
			return render(request, 'base/domain.html', {'error_msg': 'El dominio ya existe', 'domain_list': domain_list})
		except:
			pass

		d= Domains(domain= req_dict['domain'])
		alias= '@'+str(req_dict['domain'])
			#set antolinij@ardilla.com.ar como el super usuario en caso de que no exista un usuario con el dominio nuevo.
		a= Aliases(mail= alias, destination= 'antolinij@ardilla.com.ar')
		a.save()
		d.save()

		return render(request, 'base/home.html', {'domain_msg': 'Dominio agregado satisfactoriamente'} )
	else:
		#devolvemos un formulario al template
		return render(request, 'base/domain.html', {'domain_list': domain_list})

correo/templates/base/activar.html
<!DOCTYPE html>
<html>
<head>
<title>Comunicacion de Redes Seguras</title>
</head>
<body>
{% if user.is_authenticated %}

	<h3>Hola {{ user.username }}!</h3>
	<form id="secret" method="post" action="/activar/persist/">
		{% csrf_token %}
		<input type="hidden" name="secret" value="{{ secret }}"/>
		<input type="submit" value="escaneado" />
	</form>
	secret vale en ACTIVAR <br/> {{ secret }}
				  <IMG SRC="{{ url }} ">
												  <a href="/logout/">salir</a><br />
{% endif %}
</body>
</html>

correo/templates/base/base/_home-old.html
<!DOCTYPE html>
<html>
    <head>
        <title>Comunicacion de Redes Seguras</title>
    </head>
    <body>
        {% if user.is_authenticated %}
            <h3>Hola {{ user.username }}!</h3>
            	secret vale en INDEX {{ secret }} 
		{% if user.profile.secret == '0' %}
			<a href="/activar/new">Activar doble factor</a><br/>
		{% endif %}
		Tenes doble factor de autentificacion activado
		<a href="/logout/">salir</a><br />
	{% else %}
            <a href="/login/">ingresar</a><br />
	    <a href="/register/">registrarse</a><br />
        {% endif %}
    </body>
</html>

correo/templates/base/base/_register-old.html
<!DOCTYPE html>
<html>
    <head>
        <title>Login Redes Seguras</title>
    </head>
    <body>
        <h1>Register Con Django</h1>
        {% if registered %}
        Joni says: <strong>Gracias por registrarse</strong>
        <a href="/">Por favor inicie sesion</a><br />
        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Usuario: <input type="text" name="username" value="" size="50" />
            <br />
            Contraseña: <input type="password" name="password" value="" size="50" />
            <br />
             ingresar el token (en caso de tener 2F activado): <input type="text" name="token" value="" size="6" />
            <br />
           <input type="submit" value="submit" />
        </form>
	{% else %}
        Jo: <strong>registrarse</strong><br />
        asfd
        <form id="user_form" method="post" action="/register/"
                enctype="multipart/form-data">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
           <!-- Provide a button to click to submit the form. -->
            <input type="submit" name="submit" value="Register" />
        </form>
        {% endif %}
    </body>
</html>

correo/templates/base/base/activar.html
<!DOCTYPE html>
<html>
<head>
<title>Comunicacion de Redes Seguras</title>
</head>
<body>
{% if user.is_authenticated %}

	<h3>Hola {{ user.username }}!</h3>
	<form id="secret" method="post" action="/activar/persist/">
		{% csrf_token %}
		<input type="hidden" name="secret" value="{{ secret }}"/>
		<input type="submit" value="escaneado" />
	</form>
	secret vale en ACTIVAR <br/> {{ secret }}
				  <IMG SRC="{{ url }} ">
												  <a href="/logout/">salir</a><br />
{% endif %}
</body>
</html>

correo/templates/base/base/home.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Comunicacion de Redes Seguras</title>

    <!-- Bootstrap Core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/static/css/scrolling-nav.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<!-- The #page-top ID is part of the scrolling feature - the data-spy and data-target are part of the built-in Bootstrap scrollspy function -->

<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">Redes Seguras</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a class="page-scroll" href="#page-top"></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#about">Que es el doble factor de autentificacion?</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#services"><span>Doble Factor - Configuración</span></a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#contact">Datos Alumno</a>
                    </li>
		    <li>
                        <a class="page-scroll" href="/logout/">Salir</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

<!-- Intro Section -->
    <section id="intro" class="intro-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Trabajo Final - Universidad de Mendoza </br> Comunicacion de Redes Seguras</h1>
			<h3>Servicio de inicio de sesion utilizando un doble factor de seguridad</br></br></h3>
                   <p><strong>Bienvenido/a usuario/a {{ user.username }}:</strong></br>
		    {% if security == 'actived' %}
			    Actualmente tiene la seguridad en dos pasos <strong>activada</strong>.</br></br>
		    <a class="btn btn-default page-scroll" href="#services">Vea mas detalles aca</a>
		    {% else %}
                    Seguridad en dos pasos desactivada</br></br>
                    <a class="btn btn-default page-scroll" href="#about">Clic para conocer como funciona la seguridad en dos pasos</a>
                    {% endif %}
 		</div>
            </div>
        </div>
    </section>

    <!-- About Section -->
    <section id="about" class="about-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Doble Factor y su implementacion</h1><p>
			<p class="font_p" style="font-size:25px;"><strong>Breve concepto</strong></p>
				<p class="font_p" style="font-size:15px;">La seguridad en dos pasos o tambien conocido como doble factor de autentificacion se trata de una medida de seguridad extra al simple usuario y contraseña que ya conocemos.</br>
Combinando algo que el usuario sabe, un username y su password con algo que el usuario tiene, puede ser una tarjeta magnetica, recibiendo un token por correo, sms, entre otros mecanismos.</br></p>
<p class="font_p" style="font-size:25px;"><strong>Tecnologias utilizadas y sus referencias</strong></p>
                                <p class="font_p" style="font-size:15px;">
Este trabajo hace uso del software desarrollado por Google llamado Google Authentication, el cual se encuentra en el market de Android, IOS o BlackBerry <a href="https://play.google.com/store/apps/details?id=com.google.android.apps.authenticator2&hl=es_419">Google Authenticator</a>, el cliente utiliza esta herramienta para obtener</br> una contraseña de un solo uso, basandose en el algoritmo llamado Time-Based One-Time Password (TOTP) descripta en la RFC 6238 <a href="https://tools.ietf.org/html/rfc6238">RFC 6238</a>.</br></p>
<p class="font_p" style="font-size:15px;">El servidor esta implementado en python, utilizando un Framework MVC llamado Django <a href="https://www.djangoproject.com/">Django</a>aprovechando tambien un modulo llamado onetimepass <a href="https://github.com/tadeck/onetimepass">acceso a github del modulo onetimepass</a>, modulo que implementa el algoritmo (TOTP), antes mencionado.</p></br>
<p class="font_p" style="font-size:25px;"><strong>Funcionamiento de la app</strong></p>
                                <p class="font_p" style="font-size:15px;">
-Un usuario accese a nusetro servidor y se crea un usuario y contraseña, si solicita activar la seguridad doble factor, hacemos lo siguiente:</br>
-Nosotros generamos una clave pseudo-aleatoria de 10 digitos, en base al modulo Random de Python.</br>
-Codificamos esta clave en base32, lo cual nos devuelve una cadena de 16 caracteres, el cual se convertira en la clave secreta del usuario.</br>
-El cliente, en este caso un celular con Google Authenticator lee esta clave a traves de un codigo QR, la cual escanea una url con el siguiente formato:</br>

<strong>'http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=otpauth%3A//totp/'[USERNAME]'%40redes_seguras%3F[SECRET]%3D </strong></br>

- El cliente crea una clave HMAC-SHA1 usando esta clave secreta y el número de periodos de 30 segundos transcurridos desde el tiempo de Unix.</br>

 - Luego un fragmento de esta clave HMAC es extraido y se genera un codigo de 6 digitos que son entregados al usuario, el cual dura 30 segundos como maximo.</br></p>
</p>
                </div>
            </div>
        </div>
    </section>

    <!-- Services Section -->
    <section id="services" class="services-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Doble Factor de Autentificaciòn</h1>
			{% if security == 'actived' %}
				Seguridad con doble factor activada
			{% else %}
                                <IMG SRC="{{ url }} ">
				<form id="secret" method="post" action="/activar/persist/">
                			{% csrf_token %}
                			<input type="hidden" name="secret" value="{{ secret }}"/>
                			<button class="btn btn-primary btn-lg btn-block" type="submit">Codigo Escaneado</button>
        			</form>
				<strong><div class="font_p">IMPORTANTE! Una vez escaneado el codigo, presione sobre el boton Codigo Escaneado, para activar la seguridad</div></strong>
			{% endif %}
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="contact-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Contact Section</h1>
			Materia: Comunicación de Redes Seguras <br/>Alumno: Antolini, Jonathan
                        <br/>Legajo: 4957<br/>Profesor: Navarro, Diego<br/>Facultad de Ingeniería - Universidad de Mendoza</p>
                </div>
            </div>
        </div>
    </section>

    <!-- jQuery -->
    <script src="/static/js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/static/js/bootstrap.min.js"></script>

    <!-- Scrolling Nav JavaScript -->
    <script src="/static/js/jquery.easing.min.js"></script>
    <script src="/static/js/scrolling-nav.js"></script>

</body>

</html>

correo/templates/base/base/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Inicie Sesion</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="/static/css/styles.css" rel="stylesheet">
	</head>
	<body>
<!--login modal-->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h1 class="text-center">Comunicacion Redes Seguras</h1>
      </div>
      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="/login/" id="login_form">
	    {% csrf_token %}
 	    {{ error_login }}
            {{ register_msg }}
	    {{ error }}
            <div class="form-group">
              <input type="text" name="username" class="form-control input-lg" placeholder="Username">
            </div>
            <div class="form-group">
              <input type="password" name="password" class="form-control input-lg" placeholder="Password">
            </div>
            <div class="form-group">
              <input type="input" name="token" value="" class="form-control input-lg" placeholder="Token (si no tiene activada 2F, deje en blanco)">
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Iniciar sesion</button>
              <span class="pull-right"><a href="/register/">Registrarse</a></span><span>
	<!--	<a href="#">Need help?</a></span> -->
            </div>
          </form>
      </div>
	<div class="modal-footer">
          <div class="col-md-12">
          <button class="btn" data-dismiss="modal" aria-hidden="true"></button>
		  </div>	
      </div>
  </div>
  </div>
</div>
	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>
	</body>
</html>

correo/templates/base/base/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>Comunicacion de redes seguras</title>
    </head>
    <body>
        <h2>Inicio de sesion Comunicacion de Redes seguras</h2>
        {{ error_login }}
	{{ register_msg }}
	{{ secret }}
        <form id="login_form" method="post" action="/login/">
            {% csrf_token %}
            Usuario: <input type="text" name="username" value="" size="50" />
            <br />
            Contraseña: <input type="password" name="password" value="" size="50" />
            <br />
             ingresar el token (en caso de tener 2F activado): <input type="text" name="token" value="" size="6" />
            <br />
           <input type="submit" value="submit" />
         </form>
	<a href=/register/>registrarse</a>
    </body>
</html>

correo/templates/base/domain.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Comunicacion de Redes Seguras</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/font-awesome/css/font-awesome.min.css" />
    <script type="text/javascript" src="/static/js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

<div class="page-header">
    <h1>Creacion de cuentas de correo <small>Servicios de aplicacion - Univesidad de Mendoza</small></h1>
</div>

<!-- Registration form - START -->
<div class="container">
    <div class="row">
	<strong> Dominios existentes: </strong>
	<div class="form-group">
		<ul class="list-group">
                      {% for d in domain_list %}
                         <li class="list-group-item"> {{ d.domain }} </li>
		      {% endfor %}
		</ul>
         </div>

	{{ error_msg }}
        <form role="form" method="POST" action="/domain/">
	{% csrf_token %}
            <div class="col-lg-6">
                <div class="well well-sm"><strong><span class="glyphicon glyphicon-asterisk"></span>Campos requeridos</strong></div>
		<div class="form-group">
                    <label for="InputName">Dominio</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="domain" id="id_domain" placeholder="Ingrese dominio a agregar" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                </div>
		</div>
 		<button class="btn btn-primary btn-lg btn-block" type="submit">Agregar Dominio</button>
	   </div>
		<a href="/home/"> Ir a la pagina principal </a>
</div>
<!-- Registration form - END -->

</div>

</body>
</html>

correo/templates/base/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8">
		<meta charset="utf-8">
		<title>Inicie Sesion</title>
		<meta name="generator" content="Bootply" />
		<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
		<link href="/static/css/bootstrap.min.css" rel="stylesheet">
		<!--[if lt IE 9]>
			<script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]-->
		<link href="/static/css/styles.css" rel="stylesheet">
	</head>
	<body>
<!--login modal-->
<div id="loginModal" class="modal show" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
  <div class="modal-content">
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
          <h1 class="text-center">Administracion- Servidor de Correo Ardilla</h1>
      </div>
      <div class="modal-body">
          <form class="form col-md-12 center-block" method="POST" action="/login/" id="login_form">
	    {% csrf_token %}
 	    {{ error_login }}
            {{ register_msg }}
	    {{ error }}
            <div class="form-group">
              <input type="text" name="username" class="form-control input-lg" placeholder="Username">
            </div>
            <div class="form-group">
              <input type="password" name="password" class="form-control input-lg" placeholder="Password">
            </div>
            <div class="form-group">
              <button class="btn btn-primary btn-lg btn-block" type="submit">Iniciar sesion</button>
            </div>
          </form>
      </div>
	<div class="modal-footer">
          <div class="col-md-12">
          <button class="btn" data-dismiss="modal" aria-hidden="true"></button>
		  </div>	
      </div>
  </div>
  </div>
</div>
	<!-- script references -->
		<script src="//ajax.googleapis.com/ajax/libs/jquery/2.0.2/jquery.min.js"></script>
		<script src="/static/js/bootstrap.min.js"></script>
	</body>
</html>

correo/templates/base/mailbox.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Comunicacion de Redes Seguras</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="/static/font-awesome/css/font-awesome.min.css" />
    <script type="text/javascript" src="/static/js/jquery-1.10.2.min.js"></script>
    <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">

<div class="page-header">
    <h1>Creacion de cuentas de correo <small>Servicios de aplicacion - Univesidad de Mendoza</small></h1>
</div>

<!-- Registration form - START -->
<div class="container">
    <div class="row">
	{{ error_msg }}
	{{ register_msg }}
        <form role="form" method="POST" action="/mailbox/">
	{% csrf_token %}
            <div class="col-lg-6">
                <div class="well well-sm"><strong><span class="glyphicon glyphicon-asterisk"></span>Campos requeridos</strong></div>
		<div class="form-group">
                    <label for="InputName">Usuario</label>
                    <div class="input-group">
                        <input type="text" class="form-control" name="name" id="id_name" placeholder="Ingrese usuario" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
                <div class="form-group">
                    <label for="InputMessage">Contraseña</label>
                    <div class="input-group">
			<input type="password" class="form-control" id="id_crypt" name="crypt" placeholder="Ingrese su contraseña" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
		 <div class="form-group">
                    <label for="InputMessage">Repita la contraseña</label>
                    <div class="input-group">
			<input type="password" class="form-control" id="id_crypt_du" name="crypt_du" placeholder="Ingrese su contraseña" required>
                        <span class="input-group-addon"><span class="glyphicon glyphicon-asterisk"></span></span>
                    </div>
                </div>
		<div class="form-group">
			 <select class="selectpicker" name="list">
				{% for d in domain_list %}
				 <option>{{ d.domain }}</option>
				{% endfor %}
			</select>
		</div>
 		<button class="btn btn-primary btn-lg btn-block" type="submit">Crear</button>
	   </div>
	<a href="/home/">Ir a la pagina principal</a>
</div>
<!-- Registration form - END -->

</div>

</body>
</html>